# Generated by Django 5.1.4 on 2025-01-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_assessment_benchmark_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='assessment_template_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
