# Generated by Django 5.1.4 on 2025-02-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='manager',
            name='is_primary',
        ),
    ]
