# Generated by Django 5.1.4 on 2025-02-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_alter_manager_options_remove_manager_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='assessments', to='baseapp.manager'),
        ),
    ]
