# Generated by Django 5.1.4 on 2025-03-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
