# Generated by Django 5.1.4 on 2025-03-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_assessment_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
