# Generated by Django 5.1.4 on 2025-03-16 22:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_manager_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
