# Generated by Django 5.1.4 on 2025-03-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_alter_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='completion_time_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='first_accessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
